---
title: "Working with declared"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Working with declared}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(eurobarometer)
library(here)
library(dplyr)
```


The `read_sav_gesis()` function is a wrapper with [haven::read_sav](https://haven.tidyverse.org/reference/read_spss.html),  `declared:as.declared`, and [dataset::dublincore_add](https://dataset.dataobservatory.eu/reference/dublincore.html).


```{r read-example-file}
ZA5933 <- read_sav_gesis(file = system.file("extdata", "ZA5933_sample.sav", 
                                            package = "eurobarometer"))
```


```{r}
demography_vars <- get_demography_schema()
```

The original, labelled survey variables are stored as `declared`.

```{r}
demography <- ZA5933 %>%
  select( any_of( demography_vars$var_name_orig )) %>%
  mutate ( across
           (demography_vars$var_name_orig[which(demography_vars$class_target == "numeric")], as_numeric)
           ) %>%
  mutate ( across
           (demography_vars$var_name_orig[which(demography_vars$class_target == "character")], as.character)
  ) %>%
  mutate ( across
           (demography_vars$var_name_orig[which(demography_vars$class_target == "factor")], as.factor)
  ) 

```


